
services:
  parse_images:
    build: .
    image: parse:latest
    ports:
      - "8000:8000"
    env_file:
      - parse/.env
    depends_on:
      - database
  
  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data:/store
    env_file:
      - parse/.env

volumes:
  data:
